apiVersion: v1
kind: Secret
metadata:
  name: fastapi-env-secret
  namespace: default
type: Opaque
stringData:
  # --- 普通設定 (原本想放 ConfigMap 的) ---
  APP_NAME: "FastAPI Tanzu App"
  ENV: "production"
  ENABLE_METRICS: "true"
  TEMPO_ENDPOINT: "http://tempo-distributor.monitoring.svc.cluster.local:4317"
  PYROSCOPE_SERVER_ADDRESS: "http://pyroscope.monitoring.svc.cluster.local:4040"
  
  # --- 敏感設定 (原本就在 Secret 的) ---
  DB_PASSWORD: "super_secure_password_123"
  API_KEY: "sk-xxxxxxxxxxxxxxxx"
